export enum TransferCsvMutations {
  TRANSFER_CSV_MUTATION = "TRANSFER_CSV_MUTATION",
}

export enum TransferCsvGetters {
  TRANSFER_CSV_GETTER = "TRANSFER_CSV_GETTER",
}

export enum TransferCsvActions {
  TRANSFER_CSV_ACTION = "TRANSFER_CSV_ACTION",
  UPDATE_DETECT_MODAL_STATE = "UPDATE_DETECT_MODAL_STATE",
}
