export enum TagSearchMutations {
  SET_TAG_QUERY_STRING = "SET_TAG_QUERY_STRING",
  SET_SHOW_TAG_SEARCH_RESULTS = "SET_SHOW_TAG_SEARCH_RESULTS",
  SET_TAG_SEARCH_FILTERS = "SET_TAG_SEARCH_FILTERS",
}

export enum TagSearchGetters {}

export enum TagSearchActions {
  SET_TAG_QUERY_STRING = "SET_TAG_QUERY_STRING",
  SET_SHOW_TAG_SEARCH_RESULTS = "SET_SHOW_TAG_SEARCH_RESULTS",
  SET_TAG_SEARCH_FILTERS = "SET_TAG_SEARCH_FILTERS",
  PARTIAL_UPDATE_TAG_SEARCH_FILTERS = "PARTIAL_UPDATE_TAG_SEARCH_FILTERS",
  EXECUTE_QUERY = "EXECUTE_QUERY",
}
