export enum PackageSearchMutations {
  SET_EXPAND_SEARCH_ON_NEXT_LOAD = "SET_EXPAND_SEARCH_ON_NEXT_LOAD",
  SET_PACKAGE_QUERY_STRING = "SET_PACKAGE_QUERY_STRING",
  SET_SHOW_PACKAGE_SEARCH_RESULTS = "SET_SHOW_PACKAGE_SEARCH_RESULTS",
  SET_PACKAGE_SEARCH_FILTERS = "SET_PACKAGE_SEARCH_FILTERS",
  SET_SELECTED_PACKAGE_METADATA = "SET_SELECTED_PACKAGE_METADATA"
}

export enum PackageSearchGetters {}

export enum PackageSearchActions {
  SET_EXPAND_SEARCH_ON_NEXT_LOAD = "SET_EXPAND_SEARCH_ON_NEXT_LOAD",
  SET_PACKAGE_QUERY_STRING = "SET_PACKAGE_QUERY_STRING",
  SET_SHOW_PACKAGE_SEARCH_RESULTS = "SET_SHOW_PACKAGE_SEARCH_RESULTS",
  SET_PACKAGE_SEARCH_FILTERS = "SET_PACKAGE_SEARCH_FILTERS",
  PARTIAL_UPDATE_PACKAGE_SEARCH_FILTERS = "PARTIAL_UPDATE_PACKAGE_SEARCH_FILTERS",
  SET_SELECTED_PACKAGE_METADATA = "SET_SELECTED_PACKAGE_METADATA"
}
