export enum CsvFillToolMutations {
  CSV_FILL_TOOL_MUTATION = "CSV_FILL_TOOL_MUTATION",
}

export enum CsvFillToolGetters {
  CSV_FILL_TOOL_GETTER = "CSV_FILL_TOOL_GETTER",
}

export enum CsvFillToolActions {
  FILL_CSV_INTO_MODAL_FORM = "FILL_CSV_INTO_MODAL_FORM",
  ANALYZE = "ANALYZE",
  DOWNLOAD_TEMPLATE = "DOWNLOAD_TEMPLATE"
}
