export enum EmployeeSamplesState {
  INITIAL,
  LOADING,
  IDLE,
  ALLOCATION_INFLIGHT,
  ALLOCATION_SUCCESS,
  ERROR,
}

export enum EmployeeSamplesMutations {
  EMPLOYEE_SAMPLES_MUTATION = "EMPLOYEE_SAMPLES_MUTATION",
  UPDATE_DATA = "UPDATE_DATA",
}

export enum EmployeeSamplesGetters {
  SELECTED_EMPLOYEES = "SELECTED_EMPLOYEES",
  SELECTED_SAMPLE_PACKAGES = "SELECTED_SAMPLE_PACKAGES",
  SELECTED_SAMPLE_ALLOCATIONS = "SELECTED_SAMPLE_ALLOCATIONS",
  DATE_GROUPED_AVAILABLE_SAMPLE_PACKAGES = "DATE_GROUPED_AVAILABLE_SAMPLE_PACKAGES",
  ENABLE_ALLOCATION = "ENABLE_ALLOCATION",
}

export enum EmployeeSamplesActions {
  ALLOCATE_SAMPLES = "ALLOCATE_SAMPLES",
  RESET = "RESET",
  TOGGLE_EMPLOYEE = "TOGGLE_EMPLOYEE",
  TOGGLE_PACKAGE = "TOGGLE_PACKAGE",
  TOGGLE_PACKAGES_ON_DATE = "TOGGLE_PACKAGES_ON_DATE",
  TOGGLE_SAMPLE_ALLOCATION = "TOGGLE_SAMPLE_ALLOCATION",
}

export const MAX_30_DAY_FLOWER_GRAMS = 28;
export const MAX_30_DAY_CONCENTRATE_GRAMS = 6;
export const MAX_30_DAY_INFUSED_GRAMS = 2;