export enum EmployeeSamplesMutations {
  EMPLOYEE_SAMPLES_MUTATION = "EMPLOYEE_SAMPLES_MUTATION",
  UPDATE_DATA = "UPDATE_DATA",
}

export enum EmployeeSamplesGetters {
  EMPLOYEE_SAMPLES_GETTER = "EMPLOYEE_SAMPLES_GETTER",
}

export enum EmployeeSamplesActions {
  EMPLOYEE_SAMPLES_ACTION = "EMPLOYEE_SAMPLES_ACTION",
  LOAD_OBJECTS = "LOAD_OBJECTS",
}
