export enum EmployeeSamplesState {
  INITIAL,
  LOADING,
  IDLE,
  ALLOCATION_INFLIGHT,
  ALLOCATION_SUCCESS,
  ALLOCATION_ERROR,
}

export enum EmployeeSamplesMutations {
  EMPLOYEE_SAMPLES_MUTATION = "EMPLOYEE_SAMPLES_MUTATION",
  UPDATE_DATA = "UPDATE_DATA",
}

export enum EmployeeSamplesGetters {
  SELECTED_EMPLOYEES = "SELECTED_EMPLOYEES",
  SELECTED_SAMPLE_PACKAGES = "SELECTED_SAMPLE_PACKAGES",
}

export enum EmployeeSamplesActions {
  ALLOCATE_SAMPLES = "ALLOCATE_SAMPLES",
  LOAD_OBJECTS = "LOAD_OBJECTS",
  TOGGLE_EMPLOYEE = "TOGGLE_EMPLOYEE",
  TOGGLE_PACKAGE = "TOGGLE_PACKAGE",
}
