export enum PackageHistoryMutations {
  SET_SOURCE_PACKAGE = "SET_SOURCE_PACKAGE",
  SET_ANCESTORS = "SET_ANCESTORS",
  SET_CHILDREN = "SET_CHILDREN",
  SET_SOURCE_HARVESTS = "SET_SOURCE_HARVESTS",
  SET_STATUS = "SET_STATUS",
  LOG_EVENT = "LOG_EVENT",
}

export enum PackageHistoryGetters {
  ANCESTOR_LIST = "ANCESTOR_LIST",
  ANCESTOR_GENERATIONS = "ANCESTOR_GENERATIONS",
  CHILD_LIST = "CHILD_LIST",
  CHILD_GENERATIONS = "CHILD_GENERATIONS",
}

export enum PackageHistoryActions {
  SET_SOURCE_PACKAGE = "SET_SOURCE_PACKAGE",
  LOG_EVENT = "LOG_EVENT",
}

export enum PackageHistoryStatus {
  INITIAL = "INITIAL",
  INFLIGHT = "INFLIGHT",
  ERROR = "ERROR",
  SUCCESS = "SUCCESS",
}
