export enum SearchMutations {}

export enum SearchGetters {}

export enum SearchActions {
  SET_SEARCH_TYPE = 'SET_SEARCH_TYPE',
  INITIALIZE_SEARCH_TYPE = 'INITIALIZE_SEARCH_TYPE',
  SET_SHOW_SEARCH_RESULTS = 'SET_SHOW_SEARCH_RESULTS',
  SET_EXPAND_SEARCH_ON_NEXT_LOAD = 'SET_EXPAND_SEARCH_ON_NEXT_LOAD',
  SET_QUERY_STRING = 'SET_QUERY_STRING',
  EXECUTE_QUERY = 'EXECUTE_QUERY',
}

export enum SearchType {
  PACKAGES = 'PACKAGES',
  TRANSFER_PACKAGES = 'TRANSFER_PACKAGES',
  PLANTS = 'PLANTS',
  TAGS = 'TAGS',
  TRANSFERS = 'TRANSFERS',
  HARVESTS = 'HARVESTS',
  PLANT_BATCHES = 'PLANT_BATCHES',
  SALES = 'SALES',
  TRANSFER_TEMPLATES = 'TRANSFER_TEMPLATES',
}
