export enum SearchMutations {}

export enum SearchGetters {}

export enum SearchActions {
  SET_SEARCH_TYPE = "SET_SEARCH_TYPE",
  INITIALIZE_SEARCH_TYPE = "INITIALIZE_SEARCH_TYPE",
  SET_SHOW_SEARCH_RESULTS = "SET_SHOW_SEARCH_RESULTS",
  SET_EXPAND_SEARCH_ON_NEXT_LOAD = "SET_EXPAND_SEARCH_ON_NEXT_LOAD",
  SET_QUERY_STRING = "SET_QUERY_STRING",
}
