export enum LabCsvMutations {
  LAB_CSV_MUTATION = "LAB_CSV_MUTATION",
  RECORD_MESSAGE = "RECORD_MESSAGE",
  SET_METRC_FILE_ID = "SET_METRC_FILE_ID",
}

export enum LabCsvGetters {
  HAS_ERRORS = "HAS_ERRORS",
  RICH_PACKAGE_LAB_DATA = "RICH_PACKAGE_LAB_DATA",
  SHOW_OUTPUT_TABLE = "SHOW_OUTPUT_TABLE",
}

export enum LabCsvActions {
  LAB_CSV_ACTION = "LAB_CSV_ACTION",
  RESET = "RESET",
  LOAD_CSV = "LOAD_CSV",
  SELECT_COA_FILES = "SELECT_COA_FILES",
  UPLOAD_COA_FILES = "UPLOAD_COA_FILES",
  ASSIGN_COA_FILES = "ASSIGN_COA_FILES",
}

export enum LabCsvStatus {
  INITIAL = "INITIAL",
  INFLIGHT = "INFLIGHT",
  UPLOADED_CSV = "UPLOADED_CSV",
  SELECTED_COAS = "SELECTED_COAS",
  UPLOADED_COAS = "UPLOADED_COAS",
  ASSIGNED_COAS = "ASSIGNED_COAS",
}
