export enum TransferSearchMutations {
  SET_TRANSFER_QUERY_STRING = "SET_TRANSFER_QUERY_STRING",
  SET_SHOW_TRANSFER_SEARCH_RESULTS = "SET_SHOW_TRANSFER_SEARCH_RESULTS",
  SET_TRANSFER_SEARCH_FILTERS = "SET_TRANSFER_SEARCH_FILTERS",
}

export enum TransferSearchGetters {}

export enum TransferSearchActions {
  SET_TRANSFER_QUERY_STRING = "SET_TRANSFER_QUERY_STRING",
  SET_SHOW_TRANSFER_SEARCH_RESULTS = "SET_SHOW_TRANSFER_SEARCH_RESULTS",
  SET_TRANSFER_SEARCH_FILTERS = "SET_TRANSFER_SEARCH_FILTERS",
  PARTIAL_UPDATE_TRANSFER_SEARCH_FILTERS = "PARTIAL_UPDATE_TRANSFER_SEARCH_FILTERS",
  EXECUTE_QUERY = "EXECUTE_QUERY",
}
