export enum AnnouncementsMutations {
  ANNOUNCEMENTS_MUTATION = "ANNOUNCEMENTS_MUTATION",
}

export enum AnnouncementsGetters {
  ANNOUNCEMENTS_GETTER = "ANNOUNCEMENTS_GETTER",
}

export enum AnnouncementsActions {
  RESET = "RESET",
  LOAD_NOTIFICATIONS = "LOAD_NOTIFICATIONS",
  INTERVAL_LOAD_NOTIFICATIONS = "INTERVAL_LOAD_NOTIFICATIONS",
  VIEW_ANNOUNCEMENTS = "VIEW_ANNOUNCEMENTS",
}
