export const PROMOTE_IMMATURE_PLANTS_BUILDER: string = 'PromoteImmaturePlantsBuilder';

export enum PromoteImmaturePlantsBuilderMutations {
  UPDATE_PROMOTE_IMMATURE_PLANTS_DATA = 'UPDATE_PROMOTE_IMMATURE_PLANTS_DATA',
  RESET_PROMOTE_IMMATURE_PLANTS_DATA = 'RESET_PROMOTE_IMMATURE_PLANTS_DATA'
}

export enum PromoteImmaturePlantsBuilderGetters {}

export enum PromoteImmaturePlantsBuilderActions {
  UPDATE_PROMOTE_IMMATURE_PLANTS_DATA = 'UPDATE_PROMOTE_IMMATURE_PLANTS_DATA',
  RESET_PROMOTE_IMMATURE_PLANTS_DATA = 'RESET_PROMOTE_IMMATURE_PLANTS_DATA'
}
