export enum PlantSearchMutations {
  SET_EXPAND_SEARCH_ON_NEXT_LOAD = "SET_EXPAND_SEARCH_ON_NEXT_LOAD",
  SET_PLANT_QUERY_STRING = "SET_PLANT_QUERY_STRING",
  SET_SHOW_PLANT_SEARCH_RESULTS = "SET_SHOW_PLANT_SEARCH_RESULTS",
  SET_PLANT_SEARCH_FILTERS = "SET_PLANT_SEARCH_FILTERS"
}

export enum PlantSearchGetters {}

export enum PlantSearchActions {
  SET_EXPAND_SEARCH_ON_NEXT_LOAD = "SET_EXPAND_SEARCH_ON_NEXT_LOAD",
  SET_PLANT_QUERY_STRING = "SET_PLANT_QUERY_STRING",
  SET_SHOW_PLANT_SEARCH_RESULTS = "SET_SHOW_PLANT_SEARCH_RESULTS",
  SET_PLANT_SEARCH_FILTERS = "SET_PLANT_SEARCH_FILTERS",
  PARTIAL_UPDATE_PLANT_SEARCH_FILTERS = "PARTIAL_UPDATE_PLANT_SEARCH_FILTERS"
}
