export enum OmniSearchMutations {
  SET_EXPAND_SEARCH_ON_NEXT_LOAD = "SET_EXPAND_SEARCH_ON_NEXT_LOAD",
  SET_QUERY_STRING = "SET_QUERY_STRING",
  SET_SHOW_SEARCH_RESULTS = "SET_SHOW_SEARCH_RESULTS",
  SET_OMNI_SEARCH_FILTERS = "SET_OMNI_SEARCH_FILTERS",
  SET_SELECTED_OBJECT = "SET_SELECTED_OBJECT",
}

export enum OmniSearchGetters {}

export enum OmniSearchActions {
  SET_EXPAND_SEARCH_ON_NEXT_LOAD = "SET_EXPAND_SEARCH_ON_NEXT_LOAD",
  SET_QUERY_STRING = "SET_QUERY_STRING",
  SET_SHOW_SEARCH_RESULTS = "SET_SHOW_SEARCH_RESULTS",
  SET_OMNI_SEARCH_FILTERS = "SET_OMNI_SEARCH_FILTERS",
  PARTIAL_UPDATE_OMNI_SEARCH_FILTERS = "PARTIAL_UPDATE_OMNI_SEARCH_FILTERS",
  SET_SELECTED_OBJECT = "SET_SELECTED_OBJECT",
}
