export enum PluginAuthMutations {
  SET_AUTH = "SET_AUTH",
  SET_LOGIN_DATA = "SET_LOGIN_DATA",
  SET_CURRENT_USER_DATA = "SET_CURRENT_USER_DATA",
  CLEAR_LOGIN_DATA = "CLEAR_LOGIN_DATA",
  CLEAR_CURRENT_USER_DATA = "CLEAR_CURRENT_USER_DATA",
  SET_OAUTH_STATE = "SET_OAUTH_STATE",
  SET_T3API_AUTH_STATE = "SET_T3API_AUTH_STATE",
}

export enum PluginAuthGetters {
  IS_AUTHENTICATED = "IS_AUTHENTICATED",
  AUTH_STATE = "AUTH_STATE",
  PACKAGES_URL = "PACKAGES_URL",
}

export enum PluginAuthActions {
  SET_AUTH = "SET_AUTH",
  REFRESH_OAUTH_STATE = "REFRESH_OAUTH_STATE",
  REFRESH_T3API_AUTH_STATE = "REFRESH_T3API_AUTH_STATE",
}

export enum OAuthState {
  INITIAL,
  AUTHENTICATED,
  NOT_AUTHENTICATED,
}

export enum T3ApiAuthState {
  INITIAL = "INITIAL",
  AUTHENTICATED = "AUTHENTICATED",
  NOT_AUTHENTICATED = "NOT_AUTHENTICATED",
}
