export enum ReportsMutations {
  EXAMPLE_MUTATION = "EXAMPLE_MUTATION",
  SET_STATUS = "SET_STATUS",
  SET_GENERATED_SPREADSHEET = "SET_GENERATED_SPREADSHEET",
}

export enum ReportsGetters {
  EXAMPLE_GETTER = "EXAMPLE_GETTER",
}

export enum ReportsActions {
  EXAMPLE_ACTION = "EXAMPLE_ACTION",
  RESET = "RESET",
  GENERATE_REPORT_SPREADSHEET = "GENERATE_REPORT_SPREADSHEET",
}

export enum ReportStatus {
  INITIAL = "INITIAL",
  INFLIGHT = "INFLIGHT",
  SUCCESS = "SUCCESS",
  ERROR = "ERROR",
}

export enum ReportType {
  ACTIVE_PACKAGES = "ACTIVE_PACKAGES",
  OUTGOING_TRANSFERS = "OUTGOING_TRANSFERS",
  TRANSFER_PACKAGES = "TRANSFER_PACKAGES",
  MATURE_PLANTS = "MATURE_PLANTS",
  IMMATURE_PLANTS = "IMMATURE_PLANTS",
  HARVESTED_PLANTS = "HARVESTED_PLANTS",
  STRAGGLER_INVENTORY = "STRAGGLER_INVENTORY",
}
